### ISSUE TITLE
Using images or icons in links

### ISSUE THREAD

**Issue by noctivityinc** [hunterae/table-for#6]
I am trying to use font awesome icons for EDIT and DELETE methods in my table.  I have the following working:

     = t.column link_action: :edit, data: lambda { "<i class='fa fa-pencil'></i>".html_safe }    

but it looks clunky.  Is there an easier was of doing this, along the lines of (in HAML):

     = t.column link_action: :edit do
        %i.fa.fa-pencil

Which is more along the lines of standard ruby blocks for links.

**Comment by hunterae** [comment]
Hey @noctivityinc . Nice suggestion. It doesn't appear that that is currently supported in the style you suggested, but it should be. I could probably get that change together pretty quickly this week, but in the mean time, there's one improvement you could make to your one liner above if you leave out the lambda call:

```
= t.column link_action: :edit, data: "<i class='fa fa-pencil'></i>".html_safe
```

**Comment by noctivityinc** [comment]
That could work too!  Thanks.  Let me know when the block change is incorporated.






Joshua Lippiner 
.:t 704.323.5661
.:e jlippiner@noctivity.com



On December 13, 2015 at 11:01:13 PM, Andrew Hunter (notifications@github.com) wrote:

Hey @noctivityinc . Nice suggestion. It doesn't appear that that is currently supported in the style you suggested, but it should be. I could probably get that change together pretty quickly this week, but in the mean time, there's one improvement you could make to your one liner above if you leave out the lambda call:

= t.column link_action: :edit, data: "<i class='fa fa-pencil'></i>".html_safe

**Comment by hunterae** [comment]
Hey @noctivityinc , sorry for the delay. I should have a fix up for both of the issues you reported by the end of the day.

In the meantime, was wondering if you had any suggestions for how to make table-for better and how it's working for you so far.

**Comment by noctivityinc** [comment]
Im using it pretty heavily right now in my admin system and those changes you are going to make will help.

One thing that I still find missing gem wise is more of what I would call "details_table_for" or "details_for" for short.  Basically the idea is a table that is a table that would be used for details instead of typical rows of data.  In Rails terms, if table_for is for the index method,and simple_form is for new/edit then details_for would be for show.  It would basically give you a table view where the attribute names are in the left column in a th and the values are on the right.  I love table_for and simple_form, but when I need to show details for a record, I need to long hand the whole thing.

Seems like a natural extensions (think horizontal versus vertical) for table_for.

Thx!

**Comment by hunterae** [comment]
Awesome, definitely had a similar use case a while back that would have been similar. Perhaps it's about time to revisit. Thanks for the suggestion.

Also, just release version 3.4.0 of the gem that should fix your reported issue.
