### ISSUE TITLE
Global link namespace ignored since 3.4.0

### ISSUE THREAD

**Issue by panyamin** [hunterae/table-for#7]
Hello,

Since 3.4.0 `link_namespace` option is ignored when it's set on the `table_for`

**Comment by hunterae** [comment]
Hi @panyamin : thanks for letting me know. I'm fairly certain I know exactly what the problem is and will try and get a fix out shortly (and make sure that test case is covered to prevent further regressions.

**Comment by panyamin** [comment]
Hi, Ok, thank you :)

**Comment by hunterae** [comment]
@panyamin : Just pushed version 3.4.1 that should fix the issue you reported.

**Comment by panyamin** [comment]
@hunterae : awesome! it's fixed, thank you!
