### ISSUE TITLE
Undesired whitespace in td's

### ISSUE THREAD

**Issue by jfly** [hunterae/table-for#9]
The definition of `data_column` [here](https://github.com/hunterae/table-for/blob/49a4506443a47c10dcade850b51383913d508146/app/views/table_for/_table_for.html.erb#L45-L49) results in a lot of extra whitespace inside of the generated `td`, which causes problems for me when styling `td`s using CSS ::before and ::after selectors. I was able to work around this by overriding the `data_column` definition to not have whitespace, but it would be nice if `table-for` did this for me.

**Comment by hunterae** [comment]
I'm a little confused at why the extra whitespace would interfere with the ::before and ::after selectors. Can you clarify further, and possibly provide an example?

**Comment by jfly** [comment]
Check out this jsbin with 2 `<td>`s: one with extra whitespace, and one without: <https://jsbin.com/xehiyonexi>

**Comment by hunterae** [comment]
Gotcha. Thanks for the example. Let me think about that and get back to you.

**Comment by hunterae** [comment]
@jfly : try out version 3.6.0. This should address this issue, but only for td columns.

**Comment by jfly** [comment]
Thanks!
